name: trigger gitlab at unibas
on: [push]
# {{{ on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

#  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
# }}}

# TRIGGER:
# {{{ https://github.com/marketplace/actions/trigger-gitlab-ci
jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2
    # https://github.com/marketplace/actions/environment-printer
    - name: print env variables
      uses: managedkaos/print-env@master
    - name: trigger gitlab
      uses: appleboy/gitlab-ci-action@master
      with:
        host: "https://git.scicore.unibas.ch"
        token: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
        debug: true
        project_id: 1866
        ref: "main"
# }}}

# {{{ SvanBoxel/gitlab-mirror-and-ci-action
# # name: Mirror and run GitLab CI
# # on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     # - uses: actions/checkout@v1
#     - uses: actions/checkout@v2
#     - name: Mirror + trigger CI
#       uses: SvanBoxel/gitlab-mirror-and-ci-action@master
#       with:
#         args: "https://git.scicore.unibas.ch/j.piccinali/mirror_test"
#         # args: "https://gitlab.com/<namespace>/<repository>"
#       env:
#         GITLAB_HOSTNAME: "https://git.scicore.unibas.ch"
#         GITLAB_USERNAME: "j.piccinali"
#         GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
#         # <-- Generate here: https://gitlab.com/profile/personal_access_tokens
#         GITLAB_PROJECT_ID: "1866"
#         # <-- https://gitlab.com/<namespace>/<repository>/edit
#         GITHUB_TOKEN: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }} 
#         # <-- https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
# }}}

# {{{ adityakavalur/github-gitlab-ci
# # name: Mirror commits
# # on: workflow_dispatch
# jobs:
#   pushmirror:
#     runs-on: ubuntu-latest
#     env:
#       SOURCE_REPO: jgphpc/mirror_test
#       # <namespace>/<repo_name>
#       TARGET_REPO: "https://git.scicore.unibas.ch/j.piccinali/mirror_test.git"
#       # "<complete url e.g. https://gitlab.com/namespace/repository.git>"
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           repository: ${{ env.SOURCE_REPO }}
#           token: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
#           # token: ${{ secrets.SOURCE_PAT }}
#           fetch-depth: 0
#       - name: Push testing on external Gitlab
#         uses: adityakavalur/github-gitlab-ci@v0.1.1
#         with:
#           args: ${{ env.TARGET_REPO }}
#         env:
#           # TARGET_PAT: ${{ secrets.TARGET_PAT }}
#           # SOURCE_PAT: ${{ secrets.SOURCE_PAT }}
#           # GITHUB_TOKEN: ${{ secrets.SOURCE_PAT }}
#           TARGET_PAT: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
#           SOURCE_PAT: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
#           GITHUB_TOKEN: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
#           # POLL_TIMEOUT: "<Optional, value in seconds, default is 10 seconds>"
#           REPO_EVENT_TYPE: push
#           BRANCH: main
#           # APPROVAL_STRING: <Optional, approval comment that authorizes commits by non-approved users>
# }}} 

# MIRRORING:
# {{{ https://github.com/marketplace/actions/mirroring-repository needs.ssh :-(
# # name: Mirroring
# # on: [push, delete]
# jobs:
#   to_gitlab:
#     runs-on: ubuntu-18.04
#     steps:
#     # - uses: actions/checkout@v1
#     - uses: actions/checkout@v2
#     - uses: pixta-dev/repository-mirroring-action@v1
#       with:
#         target_repo_url:
#           # https://git.scicore.unibas.ch/j.piccinali/mirror_test.git
#           # git@gitlab.com:<username>/<target_repository_name>.git
#         ssh_private_key:
#           ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
# }}}

# {{{ https://github.com/marketplace/actions/mirror-repository Authentication failed :-(
# jobs:
#   to_gitlab:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: spyoungtech/mirror-action@master
#         with:
#           # REMOTE: 'https://gitlab.com/spyoungtech/mirror-action.git'
#           REMOTE: 'https://git.scicore.unibas.ch/j.piccinali/mirror_test.git'
#           GIT_USERNAME: j.piccinali
#           GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
# }}}

# {{{ https://github.com/marketplace/actions/git-mirror-action no :-(
# # name: Example
# # on: 
# #   schedule:
# #     - cron: '0 0 1-31 * *'
# jobs:
#   mirror:
#     runs-on: ubuntu-latest
#     steps:
#       - name: mirror
#         uses: mathisve/git-mirror-action@latest
#         with:
#           originalURL: https://github.com/jgphpc/mirror_test.git
#           mirrorURL: https://git.scicore.unibas.ch/j.piccinali/mirror_test.git
#           pat: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
#           # pat: ${{ secrets.GITLAB_PASSWORD }}
# }}}
